#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")"

NIX_FLAGS=(--extra-experimental-features "nix-command flakes")

nix "${NIX_FLAGS[@]}" run home-manager/release-26.05 -- switch --flake .#epita "$@"
