{ ... }:
{

  flake.nixosModules.vpsMaddy =
    { config, pkgs, ... }:
    {
      sops.secrets.maddy_noreply_password = {
        owner = config.services.maddy.user;
        restartUnits = [ "maddy-ensure-accounts.service" ];
      };
      sops.secrets.gatus_maddy_token = { };

      systemd.services.maddy-gatus = {
        description = "Report maddy health to Gatus";
        after = [
          "maddy.service"
          "network-online.target"
        ];
        wants = [ "network-online.target" ];
        path = [
          pkgs.bash
          pkgs.coreutils
          pkgs.curl
        ];
        serviceConfig = {
          Type = "oneshot";
          DynamicUser = true;
          LoadCredential = "token:${config.sops.secrets.gatus_maddy_token.path}";
        };
        script = ''
          if banner=$(timeout 5 bash -c 'exec 3<>/dev/tcp/127.0.0.1/587 && head -n1 <&3') && [[ $banner == 220* ]]; then
            query="success=true"
          else
            query="success=false&error=no+SMTP+banner+on+127.0.0.1:587"
          fi
          curl -fsS --max-time 10 -X POST \
            -H "Authorization: Bearer $(cat "$CREDENTIALS_DIRECTORY/token")" \
            "https://status.pixilie.net/api/v1/endpoints/mail_maddy/external?$query"
        '';
      };

      systemd.timers.maddy-gatus = {
        wantedBy = [ "timers.target" ];
        timerConfig = {
          OnBootSec = "1min";
          OnUnitActiveSec = "1min";
        };
      };

      services.maddy = {
        enable = true;
        hostname = "vps.pixilie.net";
        primaryDomain = "pixilie.net";
        tls.loader = "off";
        ensureCredentials."noreply@pixilie.net".passwordFile =
          config.sops.secrets.maddy_noreply_password.path;
        config = ''
          auth.pass_table local_authdb {
            table sql_table {
              driver sqlite3
              dsn credentials.db
              table_name passwords
            }
          }

          submission tcp://127.0.0.1:587 {
            limits {
              all rate 10 1s
            }
            auth &local_authdb
            source $(local_domains) {
              check {
                authorize_sender {
                  user_to_email identity
                }
              }
              default_destination {
                modify {
                  dkim $(primary_domain) $(local_domains) maddy
                }
                deliver_to &remote_queue
              }
            }
            default_source {
              reject 501 5.1.8 "Non-local sender domain"
            }
          }

          target.remote outbound_delivery {
            limits {
              destination rate 20 1s
              destination concurrency 10
            }
            mx_auth {
              dane
              mtasts {
                cache fs
                fs_dir mtasts_cache/
              }
              local_policy {
                min_tls_level encrypted
                min_mx_level none
              }
            }
          }

          target.queue remote_queue {
            target &outbound_delivery
            autogenerated_msg_domain $(primary_domain)
          }
        '';
      };
    };
}
