{ ... }:
{

  flake.nixosModules.vpsMaddy =
    { config, ... }:
    {
      sops.secrets.maddy_noreply_password = {
        owner = config.services.maddy.user;
        restartUnits = [ "maddy-ensure-accounts.service" ];
      };

      services.maddy = {
        enable = true;
        hostname = "vps.pixilie.net";
        primaryDomain = "pixilie.net";
        tls.loader = "off";
        ensureCredentials."noreply@pixilie.net".passwordFile =
          config.sops.secrets.maddy_noreply_password.path;
        config = ''
          auth.pass_table local_authdb {
            table sql_table {
              driver sqlite3
              dsn credentials.db
              table_name passwords
            }
          }

          submission tcp://127.0.0.1:587 {
            limits {
              all rate 10 1s
            }
            auth &local_authdb
            source $(local_domains) {
              check {
                authorize_sender {
                  user_to_email identity
                }
              }
              default_destination {
                modify {
                  dkim $(primary_domain) $(local_domains) maddy
                }
                deliver_to &remote_queue
              }
            }
            default_source {
              reject 501 5.1.8 "Non-local sender domain"
            }
          }

          target.remote outbound_delivery {
            limits {
              destination rate 20 1s
              destination concurrency 10
            }
            mx_auth {
              dane
              mtasts {
                cache fs
                fs_dir mtasts_cache/
              }
              local_policy {
                min_tls_level encrypted
                min_mx_level none
              }
            }
          }

          target.queue remote_queue {
            target &outbound_delivery
            autogenerated_msg_domain $(primary_domain)
          }
        '';
      };
    };
}
